In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("emp.csv")

In [3]:
df

,EmployeeID,Name,Age,Department,City,Salary,Experience,Performance,JoiningDate
0,1,Karan,41,HR,Rajkot,44592.0,20,Average,2024-02-27
1,2,Yash,44,Finance,Ahmedabad,43434.0,18,Excellent,2024-02-25
2,3,Riya,21,HR,Bhavnagar,42280.0,0,Excellent,2021-04-21
3,4,Aarav,34,HR,Vadodara,58893.0,10,Average,2023-04-21
4,5,Diya,31,IT,Vadodara,66421.0,9,Average,2021-03-16
...,...,...,...,...,...,...,...,...,...
97,98,Neha,35,HR,Ahmedabad,87091.0,9,Average,2023-04-28
98,99,Yash,29,Marketing,Vadodara,89087.0,7,Poor,2024-03-16
99,100,Rohan,31,Finance,Rajkot,33761.0,7,Average,2024-10-08
100,3,Riya,21,HR,Bhavnagar,42280.0,0,Excellent,2021-04-21
101,11,Sneha,44,Marketing,Rajkot,62087.0,22,Poor,2022-08-04

In [ ]:
# by default it consider first row as coulumn name but if you dont wnat

In [4]:
df = pd.read_csv("emp.csv" , header=None)

In [5]:
df

,0,1,2,3,4,5,6,7,8
0,EmployeeID,Name,Age,Department,City,Salary,Experience,Performance,JoiningDate
1,1,Karan,41,HR,Rajkot,44592.0,20,Average,2024-02-27
2,2,Yash,44,Finance,Ahmedabad,43434.0,18,Excellent,2024-02-25
3,3,Riya,21,HR,Bhavnagar,42280.0,0,Excellent,2021-04-21
4,4,Aarav,34,HR,Vadodara,58893.0,10,Average,2023-04-21
...,...,...,...,...,...,...,...,...,...
98,98,Neha,35,HR,Ahmedabad,87091.0,9,Average,2023-04-28
99,99,Yash,29,Marketing,Vadodara,89087.0,7,Poor,2024-03-16
100,100,Rohan,31,Finance,Rajkot,33761.0,7,Average,2024-10-08
101,3,Riya,21,HR,Bhavnagar,42280.0,0,Excellent,2021-04-21
102,11,Sneha,44,Marketing,Rajkot,62087.0,22,Poor,2022-08-04

In [6]:
# To to skip first 2 rowa
df = pd.read_csv("emp.csv" , skiprows=2)
df

      2    Yash  44    Finance  Ahmedabad  43434.0  18  Excellent  2024-02-25
0     3    Riya  21         HR  Bhavnagar  42280.0   0  Excellent  2021-04-21
1     4   Aarav  34         HR   Vadodara  58893.0  10    Average  2023-04-21
2     5    Diya  31         IT   Vadodara  66421.0   9    Average  2021-03-16
3     6  Vivaan  24    Finance  Bhavnagar      NaN   1    Average  2023-05-21
4     7   Aditi  24      Sales  Bhavnagar  79615.0   3    Average  2023-02-04
..  ...     ...  ..        ...        ...      ...  ..        ...         ...
95   98    Neha  35         HR  Ahmedabad  87091.0   9    Average  2023-04-28
96   99    Yash  29  Marketing   Vadodara  89087.0   7       Poor  2024-03-16
97  100   Rohan  31    Finance     Rajkot  33761.0   7    Average  2024-10-08
98    3    Riya  21         HR  Bhavnagar  42280.0   0  Excellent  2021-04-21
99   11   Sneha  44  Marketing     Rajkot  62087.0  22       Poor  2022-08-04

[100 rows x 9 columns]

In [7]:
pd.read_csv("emp.csv" , usecols=['Name' ,'Age'])

      Name  Age
0    Karan   41
1     Yash   44
2     Riya   21
3    Aarav   34
4     Diya   31
..     ...  ...
97    Neha   35
98    Yash   29
99   Rohan   31
100   Riya   21
101  Sneha   44

[102 rows x 2 columns]

In [8]:
type(df)

pandas.DataFrame

In [12]:
df = pd.read_csv('emp.csv')

In [ ]:
df.Name # way-1

0      Karan
1       Yash
2       Riya
3      Aarav
4       Diya
       ...
97      Neha
98      Yash
99     Rohan
100     Riya
101    Sneha
Name: Name, Length: 102, dtype: str

In [ ]:
df["Name"] # way -2

0      Karan
1       Yash
2       Riya
3      Aarav
4       Diya
       ...
97      Neha
98      Yash
99     Rohan
100     Riya
101    Sneha
Name: Name, Length: 102, dtype: str